import "@mantine/tiptap/styles.css";
import "@mantine/core/styles.css";
import {
  AppShell,
  AppShellHeader,
  AppShellMain,
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import cslocale from "dayjs/locale/cs";
import dayjs from "dayjs";
import { getLoggedInUser } from "@/utils/getLoggedInUser";

dayjs.locale(cslocale);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [
    {
      href: "/predmety",
      label: "Předměty",
    },
  ];

  const loggedInUser = await getLoggedInUser();

  if (loggedInUser?.role?.canViewAdministration) {
    menuItems.push({
      href: "/uzivatele",
      label: "Uživatelé",
    });
  }

  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <AppShell header={{ height: 60 }} padding="md">
            <AppShellHeader className="container rounded-lg shadow flex justify-end">
              <ul className="flex gap-2 p-2 items-center">
                {menuItems.map((item) => (
                  <li
                    className="px-3 py-1 bg-white rounded-lg flex"
                    key={item.href}
                  >
                    <Link href={item.href}>{item.label}</Link>
                  </li>
                ))}
              </ul>
            </AppShellHeader>

            <AppShellMain>{children}</AppShellMain>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
