import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import cslocale from "dayjs/locale/cs";
import dayjs from "dayjs";

dayjs.locale(cslocale);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  {
    href: "/subjects",
    label: "Předměty",
  },
  {
    href: "/administration",
    label: "Administrace",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-gray-800">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="container mt-2">
          <ul className="flex rounded-lg shadow gap-2 p-2 bg-blue-300">
            {menuItems.map((item) => (
              <li className="px-3 py-1 bg-white rounded-lg" key={item.href}>
                <Link href={item.href}>{item.label}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
